/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-data-generator.html
 *   arc-data-generator.js
 */

/// <reference path="arc-data-generator.d.ts" />

